variables:
  FW_VERSION_PS: '.scripts\fw-version.ps1'
  CORE_VERSION_PS: '.scripts\core-version.ps1'
  PACKAGE_PS: '.scripts\package.ps1'
  DEFAULT_SLN: 'GoC.WebTemplate.sln'
  xUNIT_PATH: 'packages\xunit.runner.console.2.4.1\tools\net461'
  TEST_FRAME_PATH: 'Components.Framework.Tests\bin\Release'
  
stages:
  - Prepare
  - Build
  - Test
  - Package
  - Deploy

include:
  - local: '/.gitlab/ci/prepare.gitlab-ci.yml'
  - local: '/.gitlab/ci/build.gitlab-ci.yml'
  - local: '/.gitlab/ci/test.gitlab-ci.yml'
  - local: '/.gitlab/ci/package.gitlab-ci.yml'
  - local: '/.gitlab/ci/deploy.gitlab-ci.yml'

.secrets:
  before_script:
    - 'copy $env:SECRETS_PATH\\GoC.WebTemplate.snk .'
  after_script:
    - 'del GoC.WebTemplate.snk'

.cache:
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths: 
      - packages/

.deploy_version:
  only:
    variables:
      - $DEPLOY_VERSION != null

Tag:
  stage: .post
  extends: .deploy_version
  tags:
    - curl
  script:
    - 'curl.exe --request POST --header "PRIVATE-TOKEN: $env:API_TOKEN" "https://gccode.ssc-spc.gc.ca/api/v4/projects/$env:CI_PROJECT_ID/repository/tags?tag_name=$env:DEPLOY_VERSION&ref=master&release_description=Automated+Release++%0D%0APlease+review+the+%5BCHANGELOG%5D%28CHANGELOG.md%29+for+details+of+the+release."'
