variables:
  VERSION_PS1: 'Builds\\version.ps1'
  DOTNET_VERSION_PS: 'Builds\\dotnet-version.ps1'
  PACKAGE_PS1: 'Builds\\package.ps1'
  DEFAULT_SLN: 'GoC.WebTemplate.sln'
  SAMPLES_SLN: 'GoC.WebTemplate.Samples.sln'
  xUNIT_PATH: 'packages\\xunit.runner.console.2.4.1\\tools\\net472'
  TEST_FRAME_PATH: 'GoC.WebTemplate.Components.Framework.Tests\\bin\\Release'
  ARTIFACTORY_DEPLOY: 'https://jade-repos.intra.dev/artifactory/ca-gc-sds-libs-nuget-local/'
  # variables from runner
  # - NUGET_PATH
  # - MSBUILD_PATH
  # - CURL_PATH
  # - ARTIFACTORY_CRED
  
stages:
  - prepare
  - build
  - test
  - package
  - deploy

include:
  - local: '/Builds/prepare.gitlab-ci.yml'
  - local: '/Builds/build.gitlab-ci.yml'
  - local: '/Builds/test.gitlab-ci.yml'
  - local: '/Builds/package.gitlab-ci.yml'
  - local: '/Builds/deploy.gitlab-ci.yml'
