build_sln:
  stage: build
  tags:
    - nuget
    - msbuild
    - secrets
  before_script:
    - 'copy %SECRETS_PATH%\\GoC.WebTemplate.snk .'
    - '"%NUGET_PATH%" restore %DEFAULT_SLN%'
  script:
    - '"%MSBUILD_PATH%" %DEFAULT_SLN% /p:Configuration=Release'
  after_script:
    - 'del GoC.WebTemplate.snk'
  artifacts:
    expire_in: 1 hour
    paths:
      - 'GoC.WebTemplate.Components\\bin\\Release'
      - 'GoC.WebTemplate.Components\\obj\\project.assets.json'
      - 'GoC.WebTemplate.Components.Core\\bin\\Release'
      - 'GoC.WebTemplate.Components.Core\\obj\\project.assets.json'
      - 'GoC.WebTemplate.Components.Framework\\bin\\Release\\GoC.WebTemplate.Components.Framework.dll'
      - 'GoC.WebTemplate.MVC\\bin\\GoC.WebTemplate.MVC.dll'
      - 'GoC.WebTemplate.WebForms\\bin\\GoC.WebTemplate.Webforms.dll'
      - '%xUNIT_PATH%'
      - '%TEST_FRAME_PATH%'

build_sample:
  stage: build
  tags:
    - nuget
    - msbuild
  before_script:
    - '"%NUGET_PATH%" restore %SAMPLES_SLN%'
  script:
    - '"%MSBUILD_PATH%" %SAMPLES_SLN% /p:Configuration=Release'