package_components:
  stage: package
  dependencies:
    - build_sln
    - version_components
  only:
    variables:
      - $MAIN_VERSION != null
  before_script:
    - dotnet restore Components/Components.csproj
  script:
    - dotnet pack "Components\\Components.csproj" --no-build -c Release -o .
  artifacts:
    expire_in: 1 day
    paths:
      - 'GoC.WebTemplate-Components.%MAIN_VERSION%.nupkg'

package_componentscore:
  stage: package
  dependencies:
    - build_sln
    - version_components # to extract proper dependency
    - version_componentscore
  only:
    variables:
      - $MAIN_VERSION != null
  script:
    - dotnet pack "Components.Core\\Components.Core.csproj" --no-build -c Release -o .
  artifacts:
    expire_in: 1 day
    paths:
      - 'GoC.WebTemplate-Components.Core.%MAIN_VERSION%.nupkg'
      
package_componentsframe:
  stage: package
  dependencies: 
    - version_componentsframe
    - build_sln
  tags:
    - nuget
  only:
    variables:
      - $MAIN_VERSION != null
  script:
    - powershell.exe "%PACKAGE_PS1%" "Components.Framework" "Components.Framework"
    - '"%NUGET_PATH%" pack "Components.Framework\\Components.Framework.nuspec"'
  artifacts:
    expire_in: 1 day
    paths:
      - 'GoC.WebTemplate-Components.Framework.%MAIN_VERSION%.nupkg'

package_coremvc:
  stage: package
  dependencies:
    - build_sln
    - version_components # to extract proper dependency
    - version_componentscore # to extract proper dependency
    - version_coremvc
  only:
    variables:
      - $MAIN_VERSION != null
  script:
    - dotnet pack "CoreMVC\\CoreMVC.csproj" --no-build -c Release -o .
  artifacts:
    expire_in: 1 day
    paths:
      - 'GoC.WebTemplate-CoreMVC.%MAIN_VERSION%.nupkg'

package_mvc:
  stage: package
  dependencies: 
    - version_mvc
    - build_sln
  tags:
    - nuget
  only:
    variables:
      - $MAIN_VERSION != null
  script:       
    - powershell.exe "%PACKAGE_PS1%" "MVC" "MVC"
    - '"%NUGET_PATH%" pack "MVC\\MVC.nuspec"'
  artifacts:
    expire_in: 1 day
    paths:
      - 'GoC.WebTemplate-MVC.%MAIN_VERSION%.nupkg'
      
package_forms:
  stage: package
  dependencies: 
    - version_forms
    - build_sln
  tags:
    - nuget
  only:
    variables:
      - $MAIN_VERSION != null
  script:   
    - powershell.exe "%PACKAGE_PS1%" "WebForms" "WebForms"
    - '"%NUGET_PATH%" pack "WebForms\\WebForms.nuspec"'    
  artifacts:
    expire_in: 1 day
    paths:
      - 'GoC.WebTemplate-WebForms.%MAIN_VERSION%.nupkg'
