package_componentsframe:
  stage: package
  dependencies: 
    - version_componentsframe
    - build_sln
  tags:
    - nuget
  only:
    variables:
      - $MAIN_VERSION != null
  script:
    - powershell.exe "%PACKAGE_PS1%" "GoC.WebTemplate.Components.Framework" "GoC.WebTemplate.Components.Framework"
    - '"%NUGET_PATH%" pack "GoC.WebTemplate.Components.Framework\\GoC.WebTemplate.Components.Framework.nuspec"'
  artifacts:
    expire_in: 1 day
    paths:
      - 'GoC.WebTemplate-Components.Framework.%MAIN_VERSION%.nupkg'

package_mvc:
  stage: package
  dependencies: 
    - version_mvc
    - build_sln
  tags:
    - nuget
  only:
    variables:
      - $MAIN_VERSION != null
  script:       
    - powershell.exe "%PACKAGE_PS1%" "GoC.WebTemplate.MVC" "GoC.WebTemplate.MVC"
    - '"%NUGET_PATH%" pack "GoC.WebTemplate.MVC\\GoC.WebTemplate.MVC.nuspec"'
  artifacts:
    expire_in: 1 day
    paths:
      - 'GoC.WebTemplate-MVC.%MAIN_VERSION%.nupkg'
      
package_forms:
  stage: package
  dependencies: 
    - version_forms
    - build_sln
  tags:
    - nuget
  only:
    variables:
      - $MAIN_VERSION != null
  script:   
    - powershell.exe "%PACKAGE_PS1%" "GoC.WebTemplate.WebForms" "GoC.WebTemplate.WebForms"
    - '"%NUGET_PATH%" pack "GoC.WebTemplate.WebForms\\GoC.WebTemplate.WebForms.nuspec"'    
  artifacts:
    expire_in: 1 day
    paths:
      - 'GoC.WebTemplate-WebForms.%MAIN_VERSION%.nupkg'

# package_mvc_sample:
#   stage: package
#   dependencies: 
#     - version_mvc_sample
#     - build_sample
#   tags:
#     - nuget
#   only:
#     - tags
#     - master
#   script:      
#     - powershell.exe "%PACKAGE_PS1%" "SampleCode\\GoC.WebTemplate-MVC.Sample" "GoC.WebTemplate-MVC.Sample"
#     - '"%NUGET_PATH%" pack "SampleCode\\GoC.WebTemplate-MVC.Sample\\GoC.WebTemplate-MVC.Sample.nuspec"' 
#   artifacts:
#     expire_in: 1 day
#     paths:
#       - 'GoC.WebTemplate-MVC.Sample.%CI_COMMIT_REF_NAME%.nupkg'

# package_forms_sample:
#   stage: package
#   dependencies: 
#     - version_froms_sample
#     - build_sample
#   tags:
#     - nuget
#   only:
#     - tags
#     - master
#   script:      
#     - powershell.exe "%PACKAGE_PS1%" "SampleCode\\GoC.WebTemplate-WebForms.Sample" "GoC.WebTemplate-WebForms.Sample"
#     - '"%NUGET_PATH%" pack "SampleCode\\GoC.WebTemplate-WebForms.Sample\\GoC.WebTemplate-WebForms.Sample.nuspec"' 
#   artifacts:
#     expire_in: 1 day
#     paths:
#       - 'GoC.WebTemplate-WebForms.Sample.%CI_COMMIT_REF_NAME%.nupkg'