version_components:
  stage: prepare
  allow_failure: true
  only:
    variables:
      - $MAIN_VERSION != null
  script:    
    - powershell.exe %DOTNET_VERSION_PS% %MAIN_VERSION% "GoC.WebTemplate.Components\GoC.WebTemplate.Components.csproj"
  artifacts:
    expire_in: 1 hour
    paths:
      - 'GoC.WebTemplate.Components\GoC.WebTemplate.Components.csproj'

version_componentscore:
  stage: prepare
  allow_failure: true
  only:
    variables:
      - $MAIN_VERSION != null
  script:    
    - powershell.exe %DOTNET_VERSION_PS% %MAIN_VERSION% "GoC.WebTemplate.Components.Core\GoC.WebTemplate.Components.Core.csproj"
  artifacts:
    expire_in: 1 hour
    paths:
      - 'GoC.WebTemplate.Components.Core\GoC.WebTemplate.Components.Core.csproj'

version_componentsframe:
  stage: prepare
  allow_failure: true
  only:
    variables:
      - $MAIN_VERSION != null
  script:    
    - powershell.exe %VERSION_PS1% %MAIN_VERSION% "GoC.WebTemplate.Components.Framework\Properties\AssemblyInfo.cs"
  artifacts:
    expire_in: 1 hour
    paths:
      - 'GoC.WebTemplate.Components.Framework\Properties\AssemblyInfo.cs'

version_coremvc:
  stage: prepare
  allow_failure: true
  only:
    variables:
      - $MAIN_VERSION != null
  script:    
    - powershell.exe %DOTNET_VERSION_PS% %MAIN_VERSION% "GoC.WebTemplate.CoreMVC\GoC.WebTemplate.CoreMVC.csproj"
  artifacts:
    expire_in: 1 hour
    paths:
      - 'GoC.WebTemplate.CoreMVC\GoC.WebTemplate.CoreMVC.csproj'

version_forms:
  stage: prepare
  allow_failure: true
  only:
    variables:
      - $MAIN_VERSION != null
  script:    
    - powershell.exe %VERSION_PS1% %MAIN_VERSION% "GoC.WebTemplate.WebForms\Properties\AssemblyInfo.cs"
  artifacts:
    expire_in: 1 hour
    paths:
      - 'GoC.WebTemplate.WebForms\Properties\AssemblyInfo.cs'

version_mvc:
  stage: prepare
  allow_failure: true
  only:
    variables:
      - $MAIN_VERSION != null
  script:    
    - powershell.exe %VERSION_PS1% %MAIN_VERSION% "GoC.WebTemplate.MVC\Properties\AssemblyInfo.cs"
  artifacts:
    expire_in: 1 hour
    paths:
      - 'GoC.WebTemplate.MVC\Properties\AssemblyInfo.cs' 
      
# version_froms_sample:
#   stage: prepare
#   allow_failure: true
#   only:
#     - tags
#   script:    
#     - powershell.exe %VERSION_PS1% %CI_COMMIT_REF_NAME% "SampleCode\GoC.WebTemplate-WebForms.Sample\Properties\AssemblyInfo.cs"
#   artifacts:
#     expire_in: 1 hour
#     paths:
#       - 'SampleCode\GoC.WebTemplate-WebForms.Sample\Properties\AssemblyInfo.cs'    
            
# version_mvc_sample:
#   stage: prepare
#   allow_failure: true
#   only:
#     - tags
#   script:    
#     - powershell.exe %VERSION_PS1% %CI_COMMIT_REF_NAME% "SampleCode\GoC.WebTemplate-MVC.Sample\Properties\AssemblyInfo.cs"
#   artifacts:
#     expire_in: 1 hour
#     paths:
#       - 'SampleCode\GoC.WebTemplate-MVC.Sample\Properties\AssemblyInfo.cs'  