Compile:Default_SLN:
  stage: Build
  extends: .secrets
  tags:
    - nuget
    - msbuild
    - secrets
    - ps
  script:
    - nuget restore $env:DEFAULT_SLN
    - msbuild $env:DEFAULT_SLN /p:Configuration=Release
  artifacts:
    expire_in: 1 hour
    paths:
      - 'Components\\bin\\Release'
      - 'Components\\obj\\project.assets.json'
      - 'Components.Core\\bin\\Release'
      - 'Components.Core\\obj\\project.assets.json'
      - 'Components.Framework\\bin\\Release\\GoC.WebTemplate.Components.Framework.dll'
      - 'CoreMVC\\bin\\Release'
      - 'CoreMVC\\obj\\project.assets.json'
      - 'MVC\\bin\\GoC.WebTemplate.MVC.dll'
      - 'WebForms\\bin\\GoC.WebTemplate.Webforms.dll'
      - '$env:xUNIT_PATH'
      - '$env:TEST_FRAME_PATH'
