.deploy:
  stage: Deploy
  tags:
    - curl
    - artifactory
    - ps
  only:
    variables:
      - $DEPLOY_VERSION != null
  environment:
    url: $env:ARTIFACTORY_DEPLOY
  script:
    - 'curl.exe -u $env:ARTIFACTORY_CRED -X PUT $env:ARTIFACTORY_DEPLOY -T GoC.WebTemplate-$env:PROJECT.$env:DEPLOY_VERSION.nupkg -k'

Deploy:Components:
  extends: .deploy
  needs: 
    - Package:Components
  variables:
    PROJECT: 'Components'
  environment:
    name: Artifactory-Components

Deploy:Components.Core:
  extends: .deploy
  needs: 
    - Package:Components.Core
  variables:
    PROJECT: 'Components.Core'
  environment:
    name: Artifactory-ComponentsCore

Deploy:Components.Framework:
  extends: .deploy
  needs: 
    - Package:Components.Framework
  variables:
    PROJECT: 'Components.Framework'
  environment:
    name: Artifactory-ComponentsFramework

Deploy:CoreMVC:
  extends: .deploy
  needs: 
    - Package:CoreMVC
  variables:
    PROJECT: 'CoreMVC'
  environment:
    name: Artifactory-CoreMVC

Deploy:MVC:
  extends: .deploy
  needs: 
    - Package:MVC
  variables:
    PROJECT: 'MVC'
  environment:
    name: Artifactory-MVC

Deploy:WebForms:
  extends: .deploy
  needs: 
    - Package:WebForms
  variables:
    PROJECT: 'WebForms'
  environment:
    name: Artifactory-WebForms
