.deploy:
  stage: Deploy
  tags:
    - curl
    - artifactory
    - ps
  environment:
    url: 'https://www.nuget.org/packages/GoC.WebTemplate-$env:PROJECT/'
    name: GoC.WebTemplate-$env:PROJECT
  only:
    variables:
      - $DEPLOY_VERSION != null
  script:
    - dotnet nuget push GoC.WebTemplate-$env:PROJECT.$env:DEPLOY_VERSION.nupkg -k $env:NUGET_DEPLOY_APIKEY -s https://api.nuget.org/v3/index.json

Deploy:Components:
  extends: .deploy
  needs: 
    - Package:Components
  variables:
    PROJECT: 'Components'

Deploy:Components.Core:
  extends: .deploy
  needs: 
    - Package:Components.Core
  variables:
    PROJECT: 'Components.Core'

Deploy:Components.Framework:
  extends: .deploy
  needs: 
    - Package:Components.Framework
  variables:
    PROJECT: 'Components.Framework'

Deploy:CoreMVC:
  extends: .deploy
  needs: 
    - Package:CoreMVC
  variables:
    PROJECT: 'CoreMVC'

Deploy:MVC:
  extends: .deploy
  needs: 
    - Package:MVC
  variables:
    PROJECT: 'MVC'

Deploy:WebForms:
  extends: .deploy
  needs: 
    - Package:WebForms
  variables:
    PROJECT: 'WebForms'
