.deploy:
  stage: Deploy
  tags:
    - curl
    - artifactory
  only:
    variables:
      - $DEPLOY_VERSION != null
  environment:
    name: Artifactory-$env:PROJECT
    url: $env:ARTIFACTORY_DEPLOY
  script:
    - 'curl -u $env:ARTIFACTORY_CRED -X PUT $env:ARTIFACTORY_DEPLOY -T GoC.WebTemplate-$env:PROJECT.$env:DEPLOY_VERSION.nupkg -k'

Deploy:Components:
  extends: .deploy
  needs: 
    - Package:Components
  variables:
    PROJECT: 'Components'

Deploy:Components.Core:
  extends: .deploy
  needs: 
    - Package:Components.Core
  variables:
    PROJECT: 'Components.Core'

Deploy:Components.Framework:
  extends: .deploy
  needs: 
    - Package:Components.Framework
  variables:
    PROJECT: 'Components.Framework'

Deploy:CoreMVC:
  extends: .deploy
  needs: 
    - Package:CoreMVC
  variables:
    PROJECT: 'CoreMVC'

Deploy:MVC:
  extends: .deploy
  needs: 
    - Package:MVC
  variables:
    PROJECT: 'MVC'

Deploy:WebForms:
  extends: .deploy
  needs: 
    - Package:WebForms
  variables:
    PROJECT: 'WebForms'
