.deploy:
  stage: Deploy
  extends: .deploy_version
  tags:
    - ps
    - dotnet
  environment:
    url: 'https://www.nuget.org/packages/GoC.WebTemplate-$env:PROJECT/'
  script:
    - 'dotnet nuget push GoC.WebTemplate-$env:PROJECT.$env:DEPLOY_VERSION.nupkg -k $env:NUGET_DEPLOY_APIKEY -s https://api.nuget.org/v3/index.json'

Deploy:Components:
  extends: .deploy
  needs: 
    - Package:Components
  variables:
    PROJECT: Components
  environment:
    name: GoC.WebTemplate-Components

Deploy:Components.Core:
  extends: .deploy
  needs: 
    - Package:Components.Core
  variables:
    PROJECT: 'Components.Core'
  environment:
    name: GoC.WebTemplate-Components.Core

Deploy:Components.Framework:
  extends: .deploy
  needs: 
    - Package:Components.Framework
  variables:
    PROJECT: 'Components.Framework'
  environment:
    name: GoC.WebTemplate-Components.Framework

Deploy:CoreMVC:
  extends: .deploy
  needs: 
    - Package:CoreMVC
  variables:
    PROJECT: 'CoreMVC'
  environment:
    name: GoC.WebTemplate-CoreMVC

Deploy:MVC:
  extends: .deploy
  needs: 
    - Package:MVC
  variables:
    PROJECT: 'MVC'
  environment:
    name: GoC.WebTemplate-MVC

Deploy:WebForms:
  extends: .deploy
  needs: 
    - Package:WebForms
  variables:
    PROJECT: 'WebForms'
  environment:
    name: GoC.WebTemplate-WebForms
