.package:
  stage: Package
  extends: .deploy_version
  artifacts:
    expire_in: 1 day
    paths:
      - 'GoC.WebTemplate-$env:PROJECT.$DEPLOY_VERSION.nupkg'

.package:core:
  extends: 
   - .package
   - .secrets #dotnet pack sometimes requires the secrets, so make sure they are there
   - .cache #if dotnet pack tries to rebuild, load cache for quicker build
  tags:
    - dotnet
    - ps
    - secrets 
  script:
    - dotnet pack $env:PROJECT\$env:PROJECT.csproj --no-build -c Release -o .

.package:fw:
  extends: .package
  tags:
    - nuget
    - ps
  script:
    - powershell.exe "$env:PACKAGE_PS" "$env:PROJECT" "$env:PROJECT"
    - nuget pack "$env:PROJECT\$env:PROJECT.nuspec"

Package:Components:
  extends: .package:core
  dependencies:
    - Compile:Default_SLN
    - Version:Components
  variables:
    PROJECT: 'Components'

Package:Components.Core:
  extends: .package:core
  dependencies:
    - Compile:Default_SLN
    - Version:Components # to extract proper dependency
    - Version:Components.Core
  variables:
    PROJECT: 'Components.Core'
      
Package:Components.Framework:
  extends: .package:fw
  dependencies:
    - Compile:Default_SLN
    - Version:Components.Framework
  variables:
    PROJECT: 'Components.Framework'

Package:CoreMVC:
  extends: .package:core
  dependencies:
    - Compile:Default_SLN
    - Version:Components # to extract proper dependency
    - Version:Components.Core # to extract proper dependency
    - Version:CoreMVC
  variables:
    PROJECT: 'CoreMVC'

Package:MVC:
  extends: .package:fw
  dependencies: 
    - Compile:Default_SLN
    - Version:MVC
  variables:
    PROJECT: 'MVC'
      
Package:WebForms:
  extends: .package:fw
  dependencies: 
    - Compile:Default_SLN
    - Version:WebForms
  variables:
    PROJECT: 'WebForms'
